# Generated by Django 5.2.3 on 2025-07-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_ingreso', models.DateField()),
                ('genero', models.CharField(max_length=50)),
                ('materia', models.CharField(max_length=50)),
                ('folio', models.CharField(max_length=20)),
                ('puntuacion_examen', models.FloatField()),
            ],
        ),
    ]
